[prune]
  go-tests = true

[[constraint]]
  version = "kubernetes-1.10.0"
  name = "k8s.io/api"

[[constraint]]
  version = "kubernetes-1.10.0"
  name = "k8s.io/apimachinery"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[override]]
  name = "github.com/openshift/generic-admission-server"
  branch = "master"

[[override]]
  name = "github.com/grafeas/client-go"
  branch = "master"
