apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: default
    name: image-signature-webhook

# to delegate authentication and authorization
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: auth-delegator-babyremote-imagewhitelist
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:auth-delegator
  subjects:
  - kind: ServiceAccount
    namespace: default
    name: image-signature-webhook

# to let the admission server read imagewhitelist/imagesecuritypolicies
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: system:babyremote:imagewhitelist
    labels:
      # Add these permissions to the "edit" default role, so that "edit" can see our CRD.
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
  rules:
  - apiGroups:
    - babyremote.com
    resources:
    - imagenamewhitelists
    verbs:
    - get
    - list
    - watch
  - apiGroups: ["grafeasprototype.github.com"] # API group created by crd
    resources: ["*"]
    verbs: ["get", "watch", "list"]

# to let aggregated apiservers create admission reviews
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: system:babyremote:imagenamewhitelists
  rules:
  - apiGroups:
    - imagenamewhitelist.babyremote.com
    resources:
    - imagenamewhitelists
    verbs:
    - create

# to let the admission server read the namespace reservations
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: image-signature-webhook-baby-remote
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: edit
  subjects:
  - kind: ServiceAccount
    name: image-signature-webhook
    namespace: default

# to read the config for terminating authentication
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: kube-system
    name: extension-server-authentication-reader-babyremote-image-signature-webhook
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    namespace: default
    name: image-signature-webhook

