apiVersion: v1
kind: Pod
metadata:
  name: nginxbreakglass
  annotations: {
    "breakglass": "true"
  }
spec:
  containers:
    - name: nginxbreakglass
      image: gcr.io/priya-wadhwa/test_image
  imagePullSecrets:
  - name: gcr-json-key
