apiVersion: v1
kind: List
items:

# to delegate authentication and authorization
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: auth-delegator-openshift-namespace-reservation
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:auth-delegator
  subjects:
  - kind: ServiceAccount
    namespace: default
    name: image-signature-webhook

# to let the admission server read the namespace reservations
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: system:openshift:online:namespace-reservation-server
  rules:
  - apiGroups:
    - babyremote.com
    resources:
    - imagenamewhitelists
    verbs:
    - get
    - list
    - watch

# to let aggregated apiservers create admission reviews
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: system:online:imagenamewhitelists
  rules:
  - apiGroups:
    - imagenamewhitelist.babyremote.com
    resources:
    - imagenamewhitelists
    verbs:
    - create

# to let the admission server read the namespace reservations
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: image-signature-webhook-baby-remote
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:babyremote:online:imagenamewhitelist
  subjects:
  - kind: ServiceAccount
    name: image-signature-webhook
    namespace: default

# to read the config for terminating authentication
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: kube-system
    name: extension-server-authentication-reader-babyremote-image-signature-webhook
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    namespace: default
    name: image-signature-webhook

